# ___________ Code to create plots  ____________#
# _____________by Anikó B. Tóth  _______________#
# ________________15 Nov 2018 __________________#
## This file contains script needed to produce plots presented in the manuscript
## Data objects used by this code are generated by Analysis_Script.R

require(ggplot2)
require(cowplot)

pdf("Figures.pdf") #optional

  ###### MAIN TEXT ########
#### FIGURE 1 ############
# need : PA
  oc <- purrr::map(PA, ~rowSums(.)/ncol(.)) %>% reduce(multimerge, by = 0, all = T)
  names(oc) <- c("Mod", "Holo", "Plei")
  
  par(mfrow = c(1,2), mar = c(3.5, 3.5, 0, 0.5), oma = c(0, 0, 1, 0), cex = 1.2)
  xmax <- .6
  plot(Plei~Holo, data = oc, pch = 16, las = 1, ylim = c(0, xmax), xlim = c(0, xmax), xlab = "Holocene occupancy", ylab = "end-Pleistocene occupancy", mgp = c(2, .7, 0))
  lines(x = c(0,.69), y = c(0,.69), lty = 2, lwd = 2)
  text("A", x = 0.05, y = xmax - 0.05, cex = 1)
  
  plot(Mod~Holo, data = oc, pch = 16, las = 1, ylim = c(0, xmax), xlim = c(0, xmax), ylab = "Recent occupancy", xlab = "Holocene occupancy", mgp = c(2, .7, 0))
  lines(x = c(0,.69), y = c(0,.69), lty = 2, lwd = 2)
  text("B", x = 0.05, y = xmax-0.05, cex = 1)


#### FIGURE 2 ##########
#arrange niche area results for plotting   
  n <- list(sv_geog, sv_clim, ss_geog, ss_clim) 
  names(n) <- c("Pleistocene_geographic range", "Pleistocene_climatic niche", "Survivor_geographic range", "Survivor_climatic niche")
  n <- bind_rows(n, .id = "group")
  n <- strsplit(n$group, fixed = TRUE, split = "_") %>% reduce(rbind) %>% data.frame(n)
  n$group <- paste(n$tbn, n$status, sep = "-")
  n$group <- factor(n$group, levels = c("MOD-survivor", "HOLO-survivor","PLEI-survivor","PLEI-victim"))

# plots 
  specs <- list(geom_density(alpha = 0.4, trim = FALSE, adjust = .8), 
                facet_wrap(~X1, scales = "free_y", shrink = FALSE, ncol = 1),
                scale_fill_manual(values = c("seagreen3", "dodgerblue", "darkslateblue", "gray35"), labels = c("Recent", "Holocene", "Pleistocene survivor", "Pleistocene victim")),
                scale_color_manual(values = c("seagreen3", "dodgerblue", "darkslateblue", "gray35"), labels = c("Recent", "Holocene", "Pleistocene survivor", "Pleistocene victim")),
                scale_y_continuous(labels = function(x) format(x, scientific = TRUE)),
                theme(panel.background = element_rect(fill = NA, color = "black"), 
                      axis.title.x = element_text(size = 12),
                      axis.text.y = element_text(size = 8),
                      panel.grid = element_blank(),
                      text = element_text(size = 12)))
  
  p1 <- ggplot(n[n$X2 == "geographic range",], aes(x = chull.area, fill = group, col = group)) +
        specs +
        geom_hline(color = "white", yintercept = 0, size = 1.4, aes(y = 0, xmin = 0, xmax = 9e06)) + 
        theme(legend.position = "none", axis.text.y = element_text(angle = 90)) +
    labs(fill = NULL, col = NULL, x = "Geographic Range (square km)", y = "Relative frequency") +
    expand_limits(x = 1.3e07) + 
    annotate("text", label = c("A", "C"), size = 4, x = Inf, y = Inf, hjust = 2, vjust = 2) + 
    panel_border(remove = FALSE, colour = "black")
  
  p2 <- ggplot(n[n$X2 == "climatic niche",], aes(x = chull.area, fill = group, col = group)) +
        specs + 
        geom_hline(color = "white", yintercept = 0, size = 1.4, aes(y = 0, xmin = 0, xmax = 20000)) + 
        theme(axis.text.y = element_text(angle = 90), 
              axis.title.y = element_blank(),
          legend.background = element_blank()) +
    labs(fill = NULL, col = NULL, x = "Climatic Niche (mm x degrees C)") +
    expand_limits(x = 23000) +
    annotate("text", label = c("B", "D"), size = 4, x = Inf, y = Inf, hjust = 2, vjust = 2) +
    panel_border(remove = FALSE, colour = "black")  
  
  p <- plot_grid(p1, p2+theme(legend.position = "none"), ncol = 2, align = "h", axis = "rl")
  plot_grid(p, get_legend(p2), ncol = 2, rel_widths = c(4,1) )
  
#### FIGURE 3 ############
  out.SS <- out[out$type == "SS",]
  out2.SS <- out.SS[out.SS$num >= ss2,]
  
  dat.summary <- out2.SS %>% group_by(timebin, subsample) %>% 
    summarize(segregations.full = percneg(SFS.ss2), 
              aggregations.full = percpos(SFS.ss2), 
              segregations.biotic = percneg(SFSa.ss2),
              aggregations.biotic = percpos(SFSa.ss2),
              segregations.abiotic = percneg(abtc.ss2),
              aggregations.abiotic = percpos(abtc.ss2))
  
  ds <- melt(dat.summary, id.vars = c("timebin", "subsample"))
  ds <- data.frame(ds, do.call(rbind, strsplit(as.character(ds$variable), split = ".", fixed = T)))
  ds$timebin <- factor(ds$timebin, levels = c("PLEI", "HOLO", "MOD"))
  ds <- na.omit(ds)
  
  p1 <- ggplot(ds, aes(x = timebin, y = value, fill = timebin)) + 
    geom_boxplot(outlier.size = 0.7, notch = TRUE, width = 0.6, size = 0.3) + 
    facet_grid(X2~X1) + 
    scale_fill_manual(values = c("darkslateblue", "dodgerblue","seagreen3")) +
    scale_x_discrete(labels = c("Pleistocene", "Holocene", "Recent")) + 
    theme(legend.position = "none", strip.text = element_text(size = 12), 
          axis.title.y = element_text(size = 12), 
          axis.text = element_text(size = 12), 
          axis.text.x = element_text(angle = 30, hjust = 1)) +
    labs(y = "Proportion", x = "") +
    annotate("text", label = c("A", "B", "C", "D", "E", "F"), size = 4, x = Inf, y = Inf, hjust = 2, vjust = 2)
    
   p1
    # if notches go outside hinges, run a higher number of reps in the script
  
#### FIGURE 4 ########
  dat.summary <- list(full = out2.SS %>% group_by(timebin, subsample, positive = posnegzero(SFS.ss2)) %>% 
                        summarize(mean = mean(SFS.ss2), median = median(SFS.ss2)),
                      biotic = out2.SS %>% group_by(timebin, subsample, positive = posnegzero(SFSa.ss2)) %>% 
                        summarize(mean = mean(SFSa.ss2), median = median(SFSa.ss2)),
                      abiotic = out2.SS %>% group_by(timebin, subsample, positive = posnegzero(abtc.ss2)) %>% 
                        summarize(mean = mean(abtc.ss2), median = median(abtc.ss2)))
  
  dat.summary <- bind_rows(dat.summary, .id = "component") %>% dplyr::filter(!positive == "ZERO")
  dat.summary$timebin <- factor(dat.summary$timebin, levels = c("PLEI", "HOLO", "MOD")) # to ensure time goes left to right on plot
  
  dat.summary$positive <- factor(dat.summary$positive)
  levels(dat.summary$positive) <- c("segregations", "aggregations")
  dat.summary$positive <- factor(dat.summary$positive, levels = c('aggregations', 'segregations'))

   
  p2 <- ggplot(dat.summary, aes(x = timebin, y = abs(mean), fill = timebin)) +  # CHANGE y = abs(mean) to y = abs(median) to get Fig. S8
    geom_boxplot(outlier.size = 0.6, width = .6, notch = TRUE, size = .3) + facet_grid(component~positive) + 
    scale_fill_manual(values = c("darkslateblue", "dodgerblue","seagreen3")) + 
    theme(legend.position = "none", axis.title.y = element_text(size = 12), 
          axis.text = element_text(size = 12), axis.text.x = element_text(angle = 30, hjust = 1), strip.text = element_text(size = 12)) +
    labs(y = "Mean weight of association", x = "") +
    scale_x_discrete(labels = c("Pleistocene", "Holocene", "Recent"))+
    annotate("text", label = c("G", "H", "I", "J", "K", "L"), size = 4, x = Inf, y = Inf, hjust = 2, vjust = 2)
  
  p2
  
  ###### SUPPLEMENT #######
  
#### FIGURE S1 ######
  modxy <- fml[which(fml$id %in% colnames(PA[[1]])),c("LONGDD", "LATDD")]
  holxy <- fml[which(fml$id %in% colnames(PA[[2]])),c("LONGDD", "LATDD")]
  plexy <- fml[which(fml$id %in% colnames(PA[[3]])),c("LONGDD", "LATDD")]
  
  par(mfrow = c(3,1), oma = c(0,0,0,0), mar = c(0, 0, 0, 0))
  
  maps::map("world", ylim = c(15, 60), xlim = c(-135, -50))
  points(fml[which(fml$id %in% colnames(PA[[1]])),c("LONGDD", "LATDD")], pch = 16, col = 'seagreen3', cex = .8)
  #polygon(modxy[chull(modxy),], border = "green3", col = rgb(0,1,0,.4))
  box()
  maps::map("world", ylim = c(15, 60), xlim = c(-135, -50))
  points(fml[which(fml$id %in% colnames(PA[[2]])),c("LONGDD", "LATDD")], pch = 16, col = 'dodgerblue', cex = .8)
  #polygon(holxy[chull(holxy),], border = "blue", col = rgb(0,0,1,.4))
  box()
  maps::map("world", ylim = c(15, 60), xlim = c(-135, -50))
  points(fml[which(fml$id %in% colnames(PA[[3]])),c("LONGDD", "LATDD")], pch = 16, col = 'darkslateblue', cex = .8)
  #polygon(plexy[chull(plexy),], border = "red", col = rgb(1,0,0,.4))
  box()
  
#### FIGURE S3 ######
  ggplot(out2.SS, aes(num, col = timebin, fill = timebin)) + 
    geom_density(alpha = 0.3, size = 1) + 
    scale_fill_manual(values = c("seagreen3", "dodgerblue","darkslateblue"), labels = c("Recent", "Holocene", "Pleistocene")) +
    scale_colour_manual(values = c("seagreen3", "dodgerblue","darkslateblue"), labels = c("Recent", "Holocene", "Pleistocene")) +
    theme(legend.position = c(0.8, 0.8), legend.text = element_text(size = 12), axis.text = element_text(size = 12), legend.title = element_blank()) +
    geom_hline(aes(yintercept = 0), col = "white", size = 1)+
    labs(x = "Number of sites in mutual niche", y = "Density")
  
  
#### FIGURE S4 ########
  dat.summary <- out2.SS %>% 
    group_by(timebin, subsample) %>% 
    summarize(Biotic = mean(abs(SFSa.ss2)), 
              Abiotic = mean(abs(abtc.ss2))) %>% 
    na.omit()
  
  dat.summary$timebin <- factor(dat.summary$timebin, levels = c("PLEI", "HOLO", "MOD"))
  ggplot(melt(dat.summary, value.name = "avgmag"), aes(x = timebin, y = avgmag, fill = timebin)) + 
    geom_boxplot(notch = TRUE) + facet_grid(~variable) + 
    scale_fill_manual(values = c("darkslateblue", "dodgerblue","seagreen3")) + 
    scale_x_discrete(labels = c("Pleistocene", "Holocene", "Recent")) + 
    theme(legend.position = "none", axis.title.y = element_text(size = 12), 
          axis.text = element_text(size = 12), axis.text.x = element_text(), strip.text = element_text(size = 12)) +
    labs(y = "Average magnitude of associations", x = "") 
  
  
  
#### FIGURE S6 ############
  md <- melt(d)
  md$timebin <- factor(md$timebin, levels = c("Recent", "Holocene", "Pleistocene"))
  
  ggplot(md, aes(pnorm(value), col = variable, fill = variable)) + 
    geom_density(size = .8) + geom_hline(aes(yintercept = 0), col = "white", size = 1) + 
    facet_grid(timebin~.) +
    scale_colour_manual(labels = c("Observed", "Fixed occupancy", "Fixed richness"), values = c(rgb(0,0,0,0), "blue", "red")) + 
    scale_fill_manual(labels = c("Observed", "Fixed occupancy", "Fixed richness"), values = c("gray", rgb(0,0,0,0), rgb(0,0,0,0))) +
    theme(legend.position = c(0.77, 0.92)) + labs(fill = NULL, col = NULL)
  
#### FIGURE S7 ############
  f <- 30 #(ylim max)
  oc <- map(PA, ~rowSums(.)/ncol(.)) %>% reduce(multimerge, by = 0, all = T)
  names(oc) <- c("Mod", "Holo", "Plei")
  suroc <- oc[which(!is.na(oc$Holo) | !is.na(oc$Mod)),]
  extoc <- oc[which(is.na(oc$Holo) & is.na(oc$Mod) ),]
  
  
  par(mfrow = c(3,1), mar = c(0,0,0,0), oma = c(4, 4, 1, 1), cex = 1)
  hist(oc[,1], xlim = c(0,.65), ylim = c(0, f), main = NA, breaks = 15, col = "gray35", las = 1, axes = F)
  hist(suroc[which(!is.na(suroc$Holo) | !is.na(suroc$Plei)),1], add = T, col = "white", breaks = 15)
  box()
  text(.55, f*0.9, "Recent", cex = 1)
  axis(2, las = 1, mgp = c(2.5,.7,0))
  
  
  hist(oc[,2], xlim = c(0,.65), ylim = c(0, f), main = NA, breaks = 15, col = "gray35", las = 1, axes = F)
  hist(suroc[which(!is.na(suroc$Mod) | !is.na(suroc$Plei)),2], add = T, col = "white", breaks = 15)
  box()
  text(.53, f*0.9, "Holocene", cex = 1)
  axis(2, las = 1, mgp = c(2.5,.7,0))
  
  mtext("Number of species", 2, line = 2.5)
  
  hist(oc[,3], xlim = c(0,.65), ylim = c(0, f), main = NA, breaks = 9, col = "gray35", las = 1, mgp = c(2.5,.7,0))
  hist(suroc[,3], add = T, col = 'white', breaks = 9)
  box()
  text(.50, f*0.9, "End-Pleistocene", cex = 1)
  
  mtext("Occupancy", 1, line = 2)
  
#### FIGURE S8 ############
  # Run Figure 4 with y = abs(median) in the ggplot aes() mapping call. 
#### FIGURE S9 and S11 ############
  # Run Analysis_Script.R with fml.sitedat <- sd.clim4k
  # Replot Figures 3 and 4
  # Replot Figure S4
  
#### FIGURE S10 and S12 ############
  # Run Analysis_Script.R with fml.sitedat <- sd.minmax1 (or any minmax1-5)
  # Replot Figures 3 and 4
  # Replot Figure S4
  
#########
  
dev.off() # optional
  
  